name: Copy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  create_docs_folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create /docs directory
      run: mkdir -p ${{ github.workspace }}/docs

  deploy_to_github_pages:
    runs-on: ubuntu-latest
    needs: create_docs_folder
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Adjust the branch as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy HTML to Pages
      run: |
        cp ./inv.html ${{ github.workspace }}/docs/inv.html

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add docs/inv.html
        git commit -m "Update GitHub Pages with latest HTML"
        git push