name: Copy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # You can change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy HTML to Pages
      run: |
        cp ../inv.html ./docs/inv.html
      working-directory: ${{ github.workspace }}
